### ISSUE TITLE
CrBrowserMain (1): EXC_BAD_ACCESS (code=1, address=0x0)

### ISSUE THREAD

**Issue by le0zh** [CefView/CocoaCefView#12]
当网页中有错误（比如网络请求错误或资源加载错误）启动时会报下面的错误：

```
CrBrowserMain (1): EXC_BAD_ACCESS (code=1, address=0x0)
```

求教如何避免？

**Comment by yuanjunxiao** [comment]
> 当网页中有错误（比如网络请求错误或资源加载错误）启动时会报下面的错误：
> 
> ```
> CrBrowserMain (1): EXC_BAD_ACCESS (code=1, address=0x0)
> ```
> 
> 求教如何避免？

你这个信息量太少了，无法定位。你是运行demo报错？还是集成到自己项目中报错？

**Comment by le0zh** [comment]
> > 当网页中有错误（比如网络请求错误或资源加载错误）启动时会报下面的错误：
> > ```
> > CrBrowserMain (1): EXC_BAD_ACCESS (code=1, address=0x0)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 求教如何避免？
> 
> 你这个信息量太少了，无法定位。你是运行demo报错？还是集成到自己项目中报错？

demo 报错，比如把 这个 https://github.com/CefView/CocoaCefView/blob/main/demo/CocoaCefViewDemo/webres/index.html#L81 script 改为一个不存在的链接， xcode 中运行就会报那个错误。

**Comment by yuanjunxiao** [comment]
> > 你这个信息量太少了，无法定位。你是运行demo报错？还是集成到自己项目中报错？
> 
> demo 报错，比如把 这个 https://github.com/CefView/CocoaCefView/blob/main/demo/CocoaCefViewDemo/webres/index.html#L81 script 改为一个不存在的链接， xcode 中运行就会报那个错误。

我暂时没有遇到过这个问题，我通过作者的工程编译出来的cocoacefView.framework 放在我们项目用的，

**Comment by le0zh** [comment]
> 我通过作者的工程编译出来的cocoacefView.framework 放在我们项目用的

@yuanjunxiao 大佬有最简化的 demo 参考么~
