### ISSUE TITLE
容器内无法播放视频，如何处理？

### ISSUE THREAD

**Issue by yuanjunxiao** [CefView/CocoaCefView#13]
![image](https://user-images.githubusercontent.com/13446025/148021835-43a4abd4-95f4-4f34-9e62-2856f1a7d702.png)
 麻烦看下，我们容器内出现这的问题，如果添加配置？

**Comment by yuanjunxiao** [comment]
查看了编译出来的framewrk 不支持h264的播放，如何配置？

**Comment by yuanjunxiao** [comment]
大哥能不能回复一下这个问题如何解决？着急中。。

**Comment by tishion** [comment]
这个，要自己编译Cef了，比较耗时，麻烦，目前没有精力支持定制化CEF，你自己尝试一下吧。

**Comment by yuanjunxiao** [comment]
> 这个，要自己编译Cef了，比较耗时，麻烦，目前没有精力支持定制化CEF，你自己尝试一下吧。

嗯。看来暂时短时间没发解决了，谢谢回复。

**Comment by yuanjunxiao** [comment]
> > 这个，要自己编译Cef了，比较耗时，麻烦，目前没有精力支持定制化CEF，你自己尝试一下吧。
> 
> 嗯。看来暂时短时间没发解决了，谢谢回复。

今天在浏览器中嵌入youtube视频是可以播放的，像优酷/腾讯视频/bibil都无法播放，这个应该是不知道html5的视频播放吧？

**Comment by tishion** [comment]
> > > 这个，要自己编译Cef了，比较耗时，麻烦，目前没有精力支持定制化CEF，你自己尝试一下吧。
> > 
> > 
> > 嗯。看来暂时短时间没发解决了，谢谢回复。
> 
> 今天在浏览器中嵌入youtube视频是可以播放的，像优酷/腾讯视频/bibil都无法播放，这个应该是不知道html5的视频播放吧？有没有解决思路？

你改改user agent，改成chrome的试试

**Comment by yuanjunxiao** [comment]
> 



> > > > 这个，要自己编译Cef了，比较耗时，麻烦，目前没有精力支持定制化CEF，你自己尝试一下吧。
> > > 
> > > 
> > > 嗯。看来暂时短时间没发解决了，谢谢回复。
> > 
> > 
> > 今天在浏览器中嵌入youtube视频是可以播放的，像优酷/腾讯视频/bibil都无法播放，这个应该是不知道html5的视频播放吧？有没有解决思路？
> 
> 你改改user agent，改成chrome的试试

不好使，我修改写死chrome的UA,还是不行。
