### ISSUE TITLE
有没有可能新增自定义的 RenderDelegate ？

### ISSUE THREAD

**Issue by le0zh** [CefView/CocoaCefView#14]
RT

如果想给 renderer 进程 js 环境注册 native 代码的话（比如 `NSPasteboard` 相关），需要自定义 RenderDelegate。

现在 CefView 中的 messge_router 和 invokeMethod 机制都只能是异步的。

我可以写在 CefViewCore 里面，但是感觉太侵入了。

**Comment by tishion** [comment]
没太明白你的需求，可否详细说明？

**Comment by le0zh** [comment]
> 没太明白你的需求，可否详细说明？

需求是要实现类似 electron 的 `clipboard.readText()` [方法](https://www.electronjs.org/docs/latest/api/clipboard#clipboardreadtexttype)，特点是：

- 在前端 js 代码中调用
- 需要有返回结果
- 是同步调用

**Comment by tishion** [comment]
invokeMethod是同步的，完全可以满足你的需求

**Comment by tishion** [comment]
> invokeMethod是同步的，完全可以满足你的需求

不支持返回值，确实目前无法满足你的需求

**Comment by tishion** [comment]
不好意思，抽空重新查看了以下代码，目前提供的所有互操作都是通过SendProcessMessage实现的，所有全部都是异步操作，因为中间需要IPC操作。

**Comment by le0zh** [comment]
嗯，我已经加了自定义的 render delegate，普通方法测试通过。

但发现读不到粘贴板数据，相同的代码放在 browser app 进程就可以，renderer 进程里就读不到，是 macos 的限制问题，还是 CEF 的问题呢？

```
NSPasteboard *pasteboard = [NSPasteboard generalPasteboard];
NSData *data = [pasteboard dataForType:NSPasteboardTypeString];
```

**Comment by le0zh** [comment]
原来是 sanbox 的原因。
