### ISSUE TITLE
CefViewWing 进程数目问题

### ISSUE THREAD

**Issue by le0zh** [CefView/CocoaCefView#15]
在 demo 中 CefViewWing 进程（非 renderer 进程）有一个，将 CocoaCefView.framework 集成到项目中后，运行有 3 个 CefViewWing 进程。

测试了下和 CefView 实例数也没有直接关系，会是因为什么导致  CefViewWing 进程数增加呢？

<img width="734" alt="image" src="https://user-images.githubusercontent.com/3633972/152716084-0b0c96bd-41b1-4364-b0b7-6b5c387f0fcd.png">

**Comment by tishion** [comment]
一个 GPU
一个 Utility
剩余的都是Render
