### ISSUE TITLE
构建时出现错误，一个是虚函数的 override 问题，一个是 abstract class 问题

### ISSUE THREAD

**Issue by laoshuaichiyu** [CefView/CocoaCefView#19]
![5121699945237_ pic](https://github.com/CefView/CocoaCefView/assets/47839581/f07f8e01-1b1f-4be6-9bc9-f8449ff55343)

这是问题的图片。
我使用的是默认的编译器，我看到cmake编译时日志显示的是AppleClang 14.0.0.14000029。
请问这个问题要怎么解决呢？

**Comment by tishion** [comment]
应该是Core的版本问题，这个项目很久没有更新了，所以请不要尝试用最新版本的core，使用这个项目里面当前提交的版本的core
