### ISSUE TITLE
请问这是基于哪个版本的CEF ? 鼠标滚轮滚动网页没有平滑效果

### ISSUE THREAD

**Issue by FlashTang** [CefView/CocoaCefView#4]
请问大佬这是基于哪个版本的CEF ? 鼠标滚轮滚动网页没有平滑效果呢？
能不能用最新的CEF?

p.s. 真是佩服大佬这等神功，我看官方cefclient例子，都不知道从哪里下手加一个按钮，好不容易加了按钮，不知道怎么设置浏览器上下左右的边距...

**Comment by tishion** [comment]
不建议升级，升级需要自己适配。
