### ISSUE TITLE
集成遇到的问题

### ISSUE THREAD

**Issue by yuanjunxiao** [CefView/CocoaCefView#7]
请问作者，集成cocoaCefView到项目必须用xib形式添加吗？我用代码集成项目一直无法成功（我是将cocoaCefView添加再viewController上面）。还有个疑问就是，必须要修改main函数入口的CocoaCefApplication吗？如果看到信息麻烦及时回复([Nib Loading] Failed to connect (window) outlet from (CocoaCefApp) to (NSWindow): missing setter or instance variable)
ok,目前通过这个已经解决了（https://developer.apple.com/forums/thread/74868）

**Comment by tishion** [comment]
解决了么？
